version: '3'

networks:
  rocketpay-network:
    driver: bridge

services:
  db:
    image: 'postgres'
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=rocketpay
    networks:
      - rocketpay-network
